#version: "3.9"
version: "3.3"
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8090"
    environment:
      - SPRING_APPLICATION_NAME=service1-app
  service2:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8082:8090"
    environment:
      - SPRING_APPLICATION_NAME=service2-app
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
